### ISSUE TITLE
Failed to parse source map 

### ISSUE THREAD

**Issue by jodusan** [ltiseni94/rosreact#1]
Hello, thanks for this cool project!

I am having a lot of messages like the following in the terminal:

```
WARNING in ./node_modules/rosreact/dist/esm/components/ImageViewer/index.js
Module Warning (from ./node_modules/source-map-loader/dist/cjs.js):
Failed to parse source map from '/home/user/Desktop/frontend/node_modules/rosreact/src/components/ImageViewer/index.ts' file: Error: ENOENT: no such file or directory, open '/home/user/Desktop/frontend/node_modules/rosreact/src/components/ImageViewer/index.ts'

```

How can I fix this?

**Comment by jodusan** [comment]
@ltiseni94 heey any ideas?

**Comment by ltiseni94** [comment]
I am sorry but I will not have the time to check this issue until next month. In the meanwhile, since this is only a warning, I hope you are still able to use the library.
