### ISSUE TITLE
What is a recommended way to publish message once?

### ISSUE THREAD

**Issue by genkv** [ltiseni94/rosreact#8]
Hi, I'm reading the source code and trying to apply it in my use case. Because I'm not too familiar with react, I wonder if there's any recommended way to only publish a message once?

Say the user click a button, and it triggers to publish a message on a topic. In the examples provided in the README, the Publisher is either repeating or latching. I wonder if I can trigger the publisher to publish only once?

Thank you very much.

**Comment by ahoenerBE** [comment]
Hi @genkv 
I'm currently working on a rework of the publisher components that includes a hook with a `publish` function.  
I just need to clean up the code and get it ready for review

**Comment by genkv** [comment]
@ahoenerBE really looking forward to it!
